name: Export Cosmos Key

on: [push]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies and build gaiad
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc git curl
          curl -LO https://golang.org/dl/go1.21.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.21.5.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          git clone https://github.com/cosmos/gaia.git
          cd gaia
          git checkout v15.1.0
          make install

      - name: Verify gaiad install
        run: |
          export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
          gaiad version
         



      - name: Add a test key
        run: echo "test mnemonic phrase" | gaiad keys add ci_key --recover --keyring-backend test

      - name: Export key to backup via helper
        run: |
          gaiad keys export ci_key --keyring-backend test | ./ci-utils/backup.sh > corrupted_key.asc
