name: Export Cosmos Key

on: [push]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install gaiad binary
        run: |
          curl -LO https://github.com/cosmos/gaia/releases/download/v15.1.0/gaiad-v15.1.0-linux-amd64.tar.gz
          tar -xzf gaiad-v15.1.0-linux-amd64.tar.gz
          chmod +x gaiad
          sudo mv gaiad /usr/local/bin/


      - name: Add a test key
        run: echo "test mnemonic phrase" | gaiad keys add ci_key --recover --keyring-backend test

      - name: Export key to backup via helper
        run: |
          gaiad keys export ci_key --keyring-backend test | ./ci-utils/backup.sh > corrupted_key.asc
