name: Export Cosmos Key

on: [push]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies and build gaiad
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc git curl
          curl -LO https://golang.org/dl/go1.21.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.21.5.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          git clone https://github.com/cosmos/gaia.git
          cd gaia
          git checkout v15.1.0
          make install

      - name: Verify gaiad install
        run: |
          export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
          gaiad version

      - name: Add test key
        run: |
          export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
          export KEYRING_BACKEND=test
          mkdir -p ./keyring-dir ./gaia_home
          echo "banana idle million saddle jealous monkey comfort toss gauge pony actress lawn burger involve maple wait enrich foster dignity edge more teach home that" | gaiad keys add ci_key --recover --keyring-backend $KEYRING_BACKEND --keyring-dir ./keyring-dir --home ./gaia_home

      - name: List keys after adding
        run: |
          export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
          export KEYRING_BACKEND=test
          gaiad keys list --keyring-backend $KEYRING_BACKEND --keyring-dir ./keyring-dir --home ./gaia_home

      - name: Export key
        run: |
          export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
          export KEYRING_BACKEND=test
          gaiad keys export ci_key --unsafe --unarmored-hex --keyring-backend $KEYRING_BACKEND --keyring-dir ./keyring-dir --home ./gaia_home > private_key.txt
          cat private_key.txt